v1.0.0 (#23)
* chore(storage): internalize ssb-postgres (#3)

* chore(ci): add tests and semantic-versionning

* chore(storage): internalize ssb-postgres

* chore(ci): init db and run tests

---------

Co-authored-by: dmba <eflorent@tbprl>

* chore(repo): push snapshot on devel

* chore(repo): push snapshot on devel

* chore(repo): push snapshot on devel

* chore(repo): push snapshot on devel

* feat(ble): initial ble configuration (wifi/owner) (#4)

* feat(ble): initial ble configuration (wifi/owner)

* chore(ci): add libsodium to test.yml


---------

Co-authored-by: dmba <eflorent@tbprl>

* fix: typo

* chore(make-pkg): fix build

* chore(github-action): upgrade checkout

* chore(github-action): typo

* feat(ble): add jest tests

* set python version

* try fix tests (#7)

* test

* test

* test

* test

* test

---------

Co-authored-by: dmba <eflorent@tbprl>

* feat(onboarding): authentication controller (#8)

* feat(onboarding): authentication controller

* fix tests

---------

Co-authored-by: dmba <eflorent@tbprl>

* fix deb-install/make-pkg.sh

* improve ble and build (#12)

improve ble and build

---------

Co-authored-by: dmba <eflorent@tbprl>

* control message size + debian fixes (#11)

* feat/get control on message limit
* fix/debian package
* feat/cleanup

Co-authored-by: dmba <eflorent@tbprl>
Co-authored-by: DMBA <emmanuel.florent@gmail.com>

* fix(chore): debian repository online via github (#13)

fix(chore): debian repository online via github (#13)

---------

Co-authored-by: dmba <eflorent@tbprl>

* fix(chore): fix debian repository publication (#14)

fix(chore): fix debian repository publication #14

---------

Co-authored-by: dmba <eflorent@tbprl>

* Feat/fix repos (#15)

* -

* -

* -

* -

* -

* -

* -

---------

Co-authored-by: dmba <eflorent@tbprl>

* Feat/fix repos (#16)

* -

* -

* -

* -

* -

* -

* -

* -

---------

Co-authored-by: dmba <eflorent@tbprl>

* Feat/fix repos (#17)

* -

* -

* -

* -

* -

* -

* -

* -

* -

---------

Co-authored-by: dmba <eflorent@tbprl>

* -

* -

* -

* -

* -

* -

* add ssb-blobs

* -

* feat: blobs networking (#18)

* -

* feat: blob networking

---------

Co-authored-by: dmba <eflorent@tbprl>

* fix: debian apt url (#19)

* -

* feat: blob networking

* fix debian apt url

---------

Co-authored-by: dmba <eflorent@tbprl>

* Update control

* Update postinst

* Update postinst

* Update postinst

* Update control

* Update postinst

* update postinst

* update postinst

* update postinst

* update postinst

* update postinst

* update postinst

* update postinst

* update package.json

* update control

* Feat/fix exchange (#20)

* fix exchange last index

* fix exchange last index

---------

Co-authored-by: dmba <eflorent@tbprl>

* fix exchange stalled + fix deps (#21)

Co-authored-by: dmba <eflorent@tbprl>

* init

* signature validation

* feat: post-delete (#22)

* feat: post-delete

---------

Co-authored-by: dmba <eflorent@tbprl>

* Merge origin/main

* merge origin/main

* add package-lock.json

---------

Co-authored-by: dmba <eflorent@tbprl>
Co-authored-by: DMBA <emmanuel.florent@gmail.com>

diff --git a/deb-install/templates/postinst b/deb-install/templates/postinst
--- a/deb-install/templates/postinst
+++ b/deb-install/templates/postinst
@@ -2,6 +2,17 @@
 set -e
 set -o pipefail
 
+
+wait_file() {
+  local file="$1"; shift
+  local wait_seconds="${1:-10}"; shift # 10 seconds as default timeout
+  test $wait_seconds -lt 1 && echo 'At least 1 second is required' && return 1
+
+  until test $((wait_seconds--)) -eq 0 -o -e "$file" ; do sleep 1; done
+
+  test $wait_seconds -ge 0 # equivalent: let ++wait_seconds
+}
+
 # User setup
 useradd --system  ssb || echo ""
 chown -R ssb:ssb /home/ssb
@@ -29,7 +40,7 @@ chown -R ssb:ssb /home/ssb/.electrum-nmc
 
 ln -s  /usr/local/Electrum-NMC/run_electrum_nmc /usr/local/bin/run_electrum_nmc  || echo "WARN: Failed to create Electrum sym link"
 
-cp /usr/lib/aarch64-linux-gnu/libsecp256k1.so.1 /usr/local/Electrum-NMC/electrum_nmc/electrum/libsecp256k1.so.0
+cp /usr/lib/*/libsecp256k1.so.1 /usr/local/Electrum-NMC/electrum_nmc/electrum/libsecp256k1.so.0
 
 
 if [ ! -f /etc/systemd/system/electrum_nmc.service ]; then
@@ -54,19 +65,25 @@ EOF
 fi
 ln -s /etc/systemd/system/electrum_nmc.service /etc/systemd/system/multi-user.target.wants/electrum_nmc.service || echo "WARN: Failed to create Electrum startup sym link"
 
+<<<<<<< HEAD
+su -c  "/usr/local/bin/run_electrum_nmc daemon & sleep 30" ssb >> /dev/null 2>&1 
+su -c "/usr/local/bin/run_electrum_nmc create" ssb >> /dev/null 2>&1  || echo "WARN: Failed to create default electrum wallet"
+su -c  "/usr/local/bin/run_electrum_nmc stop" ssb >> /dev/null 2>&1 || echo "WARN: Failed to stop electrum wallet"
+=======
 su -c  "/usr/local/bin/run_electrum_nmc daemon & sleep 30" ssb
 su -c "/usr/local/bin/run_electrum_nmc create" ssb || echo "WARN: Failed to create default electrum wallet"
 su -c  "/usr/local/bin/run_electrum_nmc stop" ssb
+>>>>>>> main
 
 
 # Postgres database setup
 su - postgres -c "psql template1 -c 'create database ssb'" || echo "WARN: Failed to create ssb database"
 su - postgres -c "psql template1 -c \"create user ssb with password 'ssb'\"" || echo "WARN: Failed to create ssb database user"
-su - postgres -c 'psql -v ON_ERROR_STOP= -qf /usr/local/ssb-relay/init.sql' || echo "WARN: Failed init ssb database"
+su - postgres -c 'psql ssb -v ON_ERROR_STOP= -qf /usr/local/ssb-relay/init.sql' || echo "WARN: Failed to init ssb database"
 
 
 # tor configuration
-if grep -xq  "^HiddenServicePort 80 127.0.0.1:8000" /etc/tor/torrc;
+if grep -xq  "HiddenServiceDir /var/lib/tor/ssb/" /etc/tor/torrc;
 then
   echo "[WARN] tor config exists skipping"
 else
@@ -77,6 +94,12 @@ HiddenServicePort 8008 127.0.0.1:8008
 EOF
 fi
 
+<<<<<<< HEAD
+systemctl restart tor
+=======
+>>>>>>> main
+
+wait_file "/var/lib/tor/ssb/hostname" 30
 
 ONION=`cat /var/lib/tor/ssb/hostname`
 
@@ -108,9 +131,7 @@ WantedBy=multi-user.target
 EOF
 fi
 
-if [ ! -f /etc/systemd/system/multi-user.target.wants/pm2-ssb.service ]; then
-  ln -s /etc/systemd/system/pm2-ssb.service /etc/systemd/system/multi-user.target.wants/pm2-ssb.service
-fi 
+env PATH=$PATH:/usr/bin /usr/local/ssb-relay/node_modules/pm2/bin/pm2 startup systemd -u ssb --hp /home/ssb
 
 mkdir -p /home/ssb/.ssb
 cp /usr/local/ssb-relay/config.example /home/ssb/.ssb/config
@@ -126,14 +147,21 @@ npm run install
 
 # allow sudo script
 # relay startup script
-if [ ! -f /etc/sudoers.d/iw ]; then
-  cat << EOF >> /etc/sudoers.d/iw
-%ssb ALL = (root) NOPASSWD: scanWIFI.sh
-%ssb ALL = (root) NOPASSWD: setWIFI.sh
-%ssb ALL = (root) NOPASSWD: cat /etc/network/interfaces.d/wlan0
+if [ ! -f /etc/sudoers.d/ssb ]; then
+  cat << EOF >> /etc/sudoers.d/ssb
+%ssb ALL = (root) NOPASSWD: /usr/local/ssb-relay/scanWIFI.sh
+%ssb ALL = (root) NOPASSWD: /usr/local/ssb-relay/setWIFI.sh
+%ssb ALL = (root) NOPASSWD: /usr/bin/cat /etc/network/interfaces.d/wlan0
 EOF
 fi
 
+
+cd /usr/local/ssb-relay/
+su ssb -c "./node_modules/.bin/pm2 start"
+su ssb -c "./node_modules/.bin/pm2 save"
+
+# https://github.com/Unitech/pm2/issues/3924
+ps aux | grep pm2 | grep -v grep | awk '{print $2}' | xargs kill -9
 
 systemctl daemon-reload
 systemctl start electrum_nmc
